apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: srs0z6wjy-python 
  janus-idp.io/tekton: srs0z6wjy-python
  backstage.io/kubernetes-id: srs0z6wjy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: srs0z6wjy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml