apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: srs0z6wjy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srs0z6wjy-python 
  name: srs0z6wjy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: srs0z6wjy-python 
